version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    tty: true
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=admin
    networks:
        - network
  
  api:
    build: 
      context: nodejs
    container_name: nodejs
    entrypoint: dockerize --wait tcp://db:3306 --timeout 20s docker-entrypoint.sh
    command: node server.js
    tty: true
    networks:
        - network
    volumes:
        - /usr/src/api
    depends_on:
        - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
        - network
    ports:
        - '8080:80'
    depends_on:
        - api

networks:
    network:
        driver: bridge


